name: Build & Push Docker Container

on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      LATEST: 14
    strategy:
      max-parallel: 4
      matrix:
        psql-version: [11, 12, 13, 14]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Create Dockerfile
        run: |
          cat << EOF > Dockerfile
          FROM alpine:latest
          RUN apk --no-cache add postgresql${{ matrix.psql-version }}-client
          ENTRYPOINT [ "psql" ]
          EOF
      - name: Build container image
        run: |
          docker build -f Dockerfile \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/psql:${{ matrix.psql-version }} \
            .
      - name: Tag Latest
        if: matrix.psql-version == env.LATEST
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/psql:${{ matrix.psql-version }} ${{ secrets.DOCKERHUB_USERNAME }}/psql:latest
      - name: Push image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/psql --all-tags